#!/usr/bin/env python3
"""Generate a SYNTHETIC .ART fixture + golden values for the Java decoder test.

We craft our own tiny .ART (NOT copyrighted game data, so it is safe to commit)
exercising both a raw frame and an RLE frame, then emit golden CRC32s of the
decoded RGBA using the validated reference decoder (art_decode.py). The Java
ArtFileTest decodes the same fixture and must reproduce these goldens.
"""

from __future__ import annotations

import os
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(__file__))
import art_decode  # noqa: E402

HERE = os.path.dirname(__file__)
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT_ART = os.path.join(REPO, "java-port", "src", "test", "resources", "art",
                       "synthetic.art")
OUT_GOLDEN = os.path.join(REPO, "java-port", "src", "test", "resources", "art",
                          "synthetic.golden")

# Palette: index 0 is the colorkey (transparent). Distinct test colors.
PALETTE = [0x000000] * 256
PALETTE[0] = 0x0000FF   # colorkey
PALETTE[1] = 0xFF0000   # red
PALETTE[2] = 0x00FF00   # green
PALETTE[3] = 0xFFFFFF   # white

W, H = 4, 4
# Frame 0: raw 4x4 (border of red, white corners, transparent centre).
FRAME0 = bytes([
    1, 3, 3, 1,
    3, 0, 0, 3,
    3, 0, 0, 3,
    1, 3, 3, 1,
])
assert len(FRAME0) == W * H


def build_art() -> bytes:
    b = bytearray()
    b += struct.pack("<I", 0x01)          # flags: bit0 -> 1 rotation
    b += struct.pack("<i", 8)             # fps
    b += struct.pack("<i", 8)             # bpp
    b += struct.pack("<4i", 0xDEAD, 0, 0, 0)   # palette_present[4] (slot 0 set)
    b += struct.pack("<i", 0)             # action_frame
    b += struct.pack("<i", 2)             # num_frames
    b += struct.pack("<8i", *([0] * 8))   # frame-table ptrs (skipped)
    # data_size[8]: frame raw=16, RLE frame computed below; per-rotation totals
    rle = _encode_rle_solid(2, W * H)     # frame1: solid green via one color run
    total = (W * H) + len(rle)
    b += struct.pack("<8i", total, 0, 0, 0, 0, 0, 0, 0)
    b += struct.pack("<8i", *([0] * 8))   # pixel-table ptrs (skipped)
    assert len(b) == art_decode.HEADER_SIZE

    # Palette (slot 0): 256 x u32 (0x00RRGGBB)
    for c in PALETTE:
        b += struct.pack("<I", c & 0x00FFFFFF)

    # Frame table (1 rotation x 2 frames)
    b += struct.pack("<7i", W, H, W * H, 1, 1, 0, 0)        # frame0: raw
    b += struct.pack("<7i", W, H, len(rle), 2, 2, 1, 1)     # frame1: rle

    # Pixel data
    b += FRAME0
    b += rle
    return bytes(b)


def _encode_rle_solid(color: int, n: int) -> bytes:
    """Encode n pixels of a single color as color-run opcodes (len<=0x7F)."""
    out = bytearray()
    left = n
    while left > 0:
        run = min(left, 0x7F)
        out.append(run)            # high bit clear -> color run
        out.append(color)
        left -= run
    return bytes(out)


def main() -> int:
    os.makedirs(os.path.dirname(OUT_ART), exist_ok=True)
    data = build_art()
    with open(OUT_ART, "wb") as f:
        f.write(data)

    art = art_decode.decode(data)            # round-trip through the reference
    lines = ["# synthetic.art golden (generated by make_art_fixture.py)",
             "flags=%d fps=%d rotations=%d frames=%d"
             % (art.flags, art.fps, art.num_rotations, art.num_frames)]
    for rot, block in enumerate(art.frames):
        for fi, fr in enumerate(block):
            rgba = art_decode.frame_to_rgba(art, fr, 0)
            crc = zlib.crc32(rgba) & 0xFFFFFFFF
            lines.append("rot%d frame%d w=%d h=%d rgba_crc32=%08X"
                         % (rot, fi, fr.width, fr.height, crc))
    with open(OUT_GOLDEN, "w") as f:
        f.write("\n".join(lines) + "\n")

    print("wrote %s (%d bytes)" % (OUT_ART, len(data)))
    print("wrote %s" % OUT_GOLDEN)
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
